    <!-- jQuery -->
    <?= $this->tag->javascriptInclude("admin/vendor/jquery/jquery.min.js") ?>

    <!-- Bootstrap Core JavaScript -->
    <?= $this->tag->javascriptInclude("admin/vendor/bootstrap/js/bootstrap.min.js") ?>

    <!-- Metis Menu Plugin JavaScript -->
    <?= $this->tag->javascriptInclude("admin/vendor/metisMenu/metisMenu.min.js") ?>

    <!-- Custom Theme JavaScript -->
    <?= $this->tag->javascriptInclude("admin/dist/js/sb-admin-2.js") ?>

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
	<script type="text/javascript">
		$('select.select2').select2();
	</script>

	<!-- CKEditor -->
	<?= $this->tag->javascriptInclude("js/ckeditor/ckeditor.js") ?>
	<script type="text/javascript">
		$(document).ready(function() {
			CKEDITOR.replace( 'ckeditor' );
		});
	</script>
</body>

</html>